<a href="https://colab.research.google.com/github/Arvin-007Elite/ML-Projects/blob/master/DataCleaning_%26_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
# df = pd.read_csv('/content/bios.csv')
# df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
98831,99627,Dan Westover,1974-03-10,NaN,NaN,NaN,United States,181.0,75.0,NaN
98832,99628,Andrew Erickson,1976-05-05,Minnetonka,Minnesota,USA,United States,180.0,74.0,NaN
98833,99629,Rob Rosser,1969-04-11,Plattsburgh,New York,USA,United States,178.0,75.0,NaN
98834,99630,V'iacheslav Derkach,1976-06-23,Pryluky,Chernihiv,UKR,Ukraine,175.0,69.0,NaN
98835,99631,Ruslan Lys,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# df.shape

(98836, 10)

In [ ]:
# df.drop_duplicates()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
98831,99627,Dan Westover,1974-03-10,NaN,NaN,NaN,United States,181.0,75.0,NaN
98832,99628,Andrew Erickson,1976-05-05,Minnetonka,Minnesota,USA,United States,180.0,74.0,NaN
98833,99629,Rob Rosser,1969-04-11,Plattsburgh,New York,USA,United States,178.0,75.0,NaN
98834,99630,V'iacheslav Derkach,1976-06-23,Pryluky,Chernihiv,UKR,Ukraine,175.0,69.0,NaN
98835,99631,Ruslan Lys,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# df.shape
# not saved

(98836, 10)

In [ ]:
# df = df.drop_duplicates()

In [ ]:
# df.shape

(98836, 10)

In [ ]:
# df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
98831,99627,Dan Westover,1974-03-10,NaN,NaN,NaN,United States,181.0,75.0,NaN
98832,99628,Andrew Erickson,1976-05-05,Minnetonka,Minnesota,USA,United States,180.0,74.0,NaN
98833,99629,Rob Rosser,1969-04-11,Plattsburgh,New York,USA,United States,178.0,75.0,NaN
98834,99630,V'iacheslav Derkach,1976-06-23,Pryluky,Chernihiv,UKR,Ukraine,175.0,69.0,NaN
98835,99631,Ruslan Lys,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# No duplicates r there
# if we have unwanted cols, we can drop it
# then if a col has words mixed with ... , \ , and any otehr unwanted charters , we have to strip it
# df['last_name'].str.lstrip("...")
# enter parameter acording what u have to strip ,
# lstrip is we particluarly tell its in left side , normal strip removes extra spaceson both sides
# now it will not save to df , becaue we only change a particular col ,
# so equal it to like this !
#  df['last_name'] = df['last_name'].str.lstrip("...")
# do sameway for whichever side , watever is there to strip
# this can be done i single line for many removals using strip giving all types in same bracket
#  df['last_name'] = df['last_name'].str.strip("./-123")

In [ ]:
# sometimes phonenumbers can be in diff format , let it be ww will format it as pure numbers
# df['phone_number'] = df['phone_number'].str.replace('[^a-zA-Z0-9]','')
# retuns a to z , and 0 to 9 all numbers , other than ths it will not print
# now it will be in pure numbers , nxtwe have to make it our country format

# before doing tht see , see if u hve NaN values int hat column , otherwise cant convert
# nan will be int and float type , convert evrything to string , because slicers r wrote in str format
# df['phone_number'] = df['phone_number'].apply(lambda x: str(x))

# then run this
# df['phone_number'] = df['phone_number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
#

In [ ]:
# removing nulls
# df['phone_number'].str.replace('NaN','')

In [1]:
# sometimes in ddress cols , more length address will there , we can separet it as region , state , district , pincode
# using split()
# df[["street Address" , "State" , "code"]] = df["Address"].str.split(',',2 , expand=True)
# if 2 commas r there separte it and make it as new col

In [2]:
# making Yes to Y , and No to N , some will be no n , y , yes formulating everything as just 2 types
# df['Paying_Customer'] = df['Paying_Customer'].str.replace('Yes','Y')
# df['Paying_Customer'] = df['Paying_Customer'].str.replace('No','N')

In [3]:
# repllacing something in whole df
# df = df.replace('N/a'," ")
#this will not change in resulr , cause its not a number

# instead of above , below is good NaN is there , cause already its not a number ,

# df = df.fillna('')

In [4]:
# now will loop thru , if a particular value is sthere , drop that row
# for x in df.index:
#   if df.loc[x,"last_name"] == 'Y':
#     df.drop(x,inplace=True)


# we can also do the same for phoen number , when the value is empty we can drop that row also , cause its unwanted
# for x in df.index:
#   if df.loc[x,"Phone_number"] == '':
#     df.drop(x,inplace=True)

# we can also do this method
# df = df.dropna((subset="Phone_number"), inplace = True)

In [ ]:
# after doing these  our indexes will be in wrong order ,
# we can rest the index  in order
# df = df.reset_index()
# with this old index vaue will also store so , dont want that , use below line
# df = df.reset_index(drop=True)
# now everthing will be in order

In [5]:
df = pd.read_excel('/content/olympics-data.xlsx')
df

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [6]:
# if our data contain big numbers , with more decimal values , we can convert it to limited normal numbers !
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [8]:
df.describe()

       athlete_id  height_cm  weight_kg
count   145500.00  106651.00  102070.00
mean     73686.19     176.33      71.89
std      42868.96      10.38      14.47
min          1.00     127.00      25.00
25%      36663.75     170.00      62.00
50%      73302.50     176.00      70.00
75%     110306.25     183.00      80.00
max     149814.00     226.00     198.00

In [10]:
df.isnull().sum()
# finding missing datas

athlete_id           0
name                 0
born_date         1807
born_city        34592
born_region      34592
born_country     34592
NOC                  1
height_cm        38849
weight_kg        43430
died_date       111560
dtype: int64

In [11]:
df.nunique()

athlete_id      145500
name            142780
born_date        41279
born_city        22368
born_region       2554
born_country       236
NOC                696
height_cm           95
weight_kg          141
died_date        20009
dtype: int64

In [12]:
df.sort_values(by="born_region").head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
134942,138062,Dimitri Isler,1993-05-14,Aarau,Aargau,SUI,Switzerland,175.00,75.00,NaN
32428,32671,Max Schär,1953-06-12,Zofingen,Aargau,SUI,Switzerland,197.00,94.00,NaN
75169,75746,Daria Nauer,1966-05-21,Wettingen,Aargau,SUI,Switzerland,168.00,50.00,NaN
133039,135954,Daniel Wiederkehr,1989-05-15,Baden,Aargau,SUI,Switzerland,183.00,73.00,NaN
133037,135952,Ciril Grossklaus,1991-04-17,Brugg,Aargau,SUI,Switzerland,185.00,90.00,NaN

In [14]:
print(df.dtypes)

athlete_id        int64
name             object
born_date        object
born_city        object
born_region      object
born_country     object
NOC              object
height_cm       float64
weight_kg       float64
died_date        object
dtype: object

In [21]:
# df.groupby('born_country').mean()
# df[df['NOC'].str.contains('Switzerland')]
# df.groupby('born_country').mean().sort_values(by="NOC")

In [22]:
# we can transose our indexes to columns , and cols to indexes
# df3 = df2.transpose()
# we can easily use labes to plot
df.columns

Index(['athlete_id', 'name', 'born_date', 'born_city', 'born_region',
       'born_country', 'NOC', 'height_cm', 'weight_kg', 'died_date'],
      dtype='object')

In [23]:
# to return only numerical cols
df.select_dtypes(include='number')
# if u put object strings will come !  orcan use float

        athlete_id  height_cm  weight_kg
0                1        NaN        NaN
1                2     183.00      76.00
2                3     183.00      76.00
3                4     168.00      64.00
4                5        NaN        NaN
...            ...        ...        ...
145495      149222     167.00      61.00
145496      149223     168.00      65.00
145497      149224     163.00      55.00
145498      149225     166.00        NaN
145499      149814        NaN        NaN

[145500 rows x 3 columns]